export const LOADING_PHRASES = [
  { text: "Summoning the senpai of all books...", emoji: "😘" },
  { text: "Chasing waifus through the library...", emoji: "🏃‍♂️" },
  { text: "Unleashing the power of 1000 anime episodes...", emoji: "✨" },
  { text: "Oppai overload, please wait...", emoji: "🍑" },
  { text: "Searching for the ultimate tsundere tale...", emoji: "😤" },
  { text: "Loading the harem of your dreams...", emoji: "😍" },
  { text: "Baka, it’s not that easy to find these books!", emoji: "😣" },
  { text: "Channeling my inner shonen hero...", emoji: "💪" },
  { text: "Yandere vibes incoming, hold tight...", emoji: "🔪" },
  { text: "Ecchi pages flipping at max speed...", emoji: "📖" },
  { text: "Senpai, your books are almost here...", emoji: "🥰" },
  { text: "Doki doki, fetching your favorites...", emoji: "❤️" },
  { text: "Loading the ultimate kawaii collection...", emoji: "🌸" },
  { text: "Nya~ Books are purring into place...", emoji: "😺" },
  { text: "Hentai gods approve this loading screen...", emoji: "🙏" },
  { text: "Slicing through dimensions to find your books...", emoji: "⚔️" },
  { text: "Mecha suits powering up for your search...", emoji: "🤖" },
  { text: "It’s over 9000! Wait, just books...", emoji: "📚" },
  { text: "Blushing while loading spicy stories...", emoji: "😳" },
  { text: "Onee-san is preparing your reads...", emoji: "👩‍🏫" },
  { text: "Kawaii overload, system stabilizing...", emoji: "🐾" },
  { text: "Fetching the forbidden scrolls...", emoji: "🧧" },
  { text: "Isekai portal opening for your books...", emoji: "🚪" },
  { text: "Loading with the speed of a shinkansen...", emoji: "🚅" },
  { text: "Ara ara, your books are coming...", emoji: "😏" },
  { text: "Catgirls are sorting your library...", emoji: "😽" },
  { text: "Powering up the nakama spirit...", emoji: "🤝" },
  { text: "Loading with maximum dere energy...", emoji: "😻" },
  { text: "Summoning the loli librarian...", emoji: "📖" },
  { text: "Plot twist: still loading your books...", emoji: "😜" },
];